import type {
  Pilgrim,
  Booking,
  PackageBatch,
  Hotel,
  RoomAllocation,
  TransportAllocation,
  FlightManifest,
  Lead,
  SubAgent,
  FinancialTransaction,
  AuditLog,
} from '../types';

export const INITIAL_HOTELS: Hotel[] = [
  {
    id: 'htl-makkah-01',
    city: 'Makkah',
    name: 'Fairmont Clock Royal Tower Makkah',
    nameAr: 'فندق برج ساعة مكة فيرمونت',
    rating: 5,
    distanceToHaram: '0m (Direct Haram View & Access)',
    address: 'King Abdul Aziz Endowment, Abraj Al Bait Complex, Makkah',
    addressAr: 'مجمع أبراج البيت، وقف الملك عبد العزيز، مكة المكرمة',
    googleMapUrl: 'https://maps.google.com/?q=Fairmont+Makkah',
    receptionPhone: '+966 12 571 7777',
    managerName: 'Sheikh Tariq Al-Ghamdi',
    totalRooms: 40,
    image: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'htl-makkah-02',
    city: 'Makkah',
    name: 'Swissôtel Al Maqam Makkah',
    nameAr: 'سويس أوتيل المقام مكة',
    rating: 5,
    distanceToHaram: '20m (Clock Tower Complex)',
    address: 'Abraj Al Bait Complex, Ibrahim Al Khalil St, Makkah',
    addressAr: 'أبراج البيت، شارع إبراهيم الخليل، مكة المكرمة',
    googleMapUrl: 'https://maps.google.com/?q=Swissotel+Al+Maqam+Makkah',
    receptionPhone: '+966 12 577 0000',
    managerName: 'Ahmed Mansoor',
    totalRooms: 35,
    image: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'htl-makkah-03',
    city: 'Makkah',
    name: 'Al Safwah Royale Orchid Makkah',
    nameAr: 'الصفوة رويال أوركيد مكة',
    rating: 5,
    distanceToHaram: '0m (Direct King Abdulaziz Gate 1)',
    address: 'Ajyad Street, Facing King Abdulaziz Gate, Makkah',
    addressAr: 'شارع أجياد، أمام بوابة الملك عبد العزيز، مكة المكرمة',
    googleMapUrl: 'https://maps.google.com/?q=Al+Safwah+Royale+Orchid',
    receptionPhone: '+966 12 576 8888',
    managerName: 'Bandar Al-Otaibi',
    totalRooms: 30,
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'htl-madinah-01',
    city: 'Madinah',
    name: 'Anwar Al Madinah Mövenpick Hotel',
    nameAr: 'فندق أنوار المدينة موفنبيك',
    rating: 5,
    distanceToHaram: '0m (Direct Northern Courtyard Access)',
    address: 'Central Northern Area, Facing Prophet Mosque Gate 15, Madinah',
    addressAr: 'المنطقة المركزية الشمالية، أمام الحرم النبوي بوابة 15، المدينة المنورة',
    googleMapUrl: 'https://maps.google.com/?q=Anwar+Al+Madinah+Movenpick',
    receptionPhone: '+966 14 818 1000',
    managerName: 'Sultan Al-Harbi',
    totalRooms: 45,
    image: 'https://images.unsplash.com/photo-1580418827493-f2b22c0a76cb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'htl-madinah-02',
    city: 'Madinah',
    name: 'Dar Al Taqwa Hotel Madinah',
    nameAr: 'فندق دار التقوى المدينة',
    rating: 5,
    distanceToHaram: '10m (Facing Prophet Mosque Ladies Gate)',
    address: 'Off Main Court, Facing King Fahd Gate, Madinah',
    addressAr: 'الساحة الرئيسية، أمام بوابة الملك فهد، المدينة المنورة',
    googleMapUrl: 'https://maps.google.com/?q=Dar+Al+Taqwa+Madinah',
    receptionPhone: '+966 14 829 1111',
    managerName: 'Fahad Al-Zahrani',
    totalRooms: 25,
    image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_PACKAGES: PackageBatch[] = [
  {
    id: 'pkg-hajj-2026',
    code: 'HAJJ-2026-VIP',
    title: 'Hajj 2026 — Executive Shifting VIP (21 Days)',
    titleAr: 'حج 1447هـ — باقة كبار الشخصيات التنفيذية (21 يوم)',
    type: 'fixed_departure',
    durationDays: 21,
    departureCity: 'Mumbai (BOM)',
    departureDate: '2026-05-20',
    returnDate: '2026-06-10',
    totalSeats: 50,
    availableSeats: 8,
    pricing: {
      quadSharingInr: 785000,
      tripleSharingInr: 845000,
      doubleSharingInr: 965000,
      singleSharingInr: 1250000,
    },
    costBreakdown: {
      flightFareInr: 125000,
      makkahHotelSarPerNight: 2800,
      madinahHotelSarPerNight: 2200,
      makkahNights: 12,
      madinahNights: 9,
      visaInsuranceInr: 45000,
      transportSarPerPerson: 1800,
      cateringSarPerDay: 180,
      ziyaratSar: 450,
      maktabMutawwifSar: 12500,
      targetMarginInr: 85000,
      gstPercentage: 5,
    },
    makkahHotelName: 'Fairmont Clock Royal Tower Makkah',
    makkahHotelDistance: '0m Haram Facing',
    madinahHotelName: 'Anwar Al Madinah Mövenpick Hotel',
    madinahHotelDistance: '0m Direct Northern Gate',
    airlineName: 'Saudia (Saudi Arabian Airlines)',
    flightRoute: 'BOM ➔ JED (Direct) / MED ➔ BOM (Direct)',
    status: 'filling_fast',
  },
  {
    id: 'pkg-umrah-sep-2026',
    code: 'UMRAH-SEP-DELUXE',
    title: 'Umrah — Autumn Deluxe 15 Days (Sep 2026)',
    titleAr: 'عمرة الخريف الفاخرة — 15 يوم (سبتمبر 2026)',
    type: 'fixed_departure',
    durationDays: 15,
    departureCity: 'Mumbai (BOM)',
    departureDate: '2026-09-15',
    returnDate: '2026-09-30',
    totalSeats: 45,
    availableSeats: 12,
    pricing: {
      quadSharingInr: 138000,
      tripleSharingInr: 152000,
      doubleSharingInr: 175000,
      singleSharingInr: 225000,
    },
    costBreakdown: {
      flightFareInr: 42000,
      makkahHotelSarPerNight: 950,
      madinahHotelSarPerNight: 750,
      makkahNights: 8,
      madinahNights: 7,
      visaInsuranceInr: 15500,
      transportSarPerPerson: 550,
      cateringSarPerDay: 90,
      ziyaratSar: 250,
      targetMarginInr: 18000,
      gstPercentage: 5,
    },
    makkahHotelName: 'Swissôtel Al Maqam Makkah',
    makkahHotelDistance: '20m Clock Tower',
    madinahHotelName: 'Dar Al Taqwa Hotel Madinah',
    madinahHotelDistance: '10m Ladies Gate',
    airlineName: 'Saudia (Saudi Arabian Airlines)',
    flightRoute: 'BOM ➔ JED / MED ➔ BOM',
    status: 'open',
  },
  {
    id: 'pkg-ramadan-2026',
    code: 'RAMADAN-2026-LAST10',
    title: 'Ramadan 2026 — Blessed Last 10 Days Al Safwah',
    titleAr: 'عمرة العشر الأواخر من رمضان 1447هـ — برج الصفوة',
    type: 'fixed_departure',
    durationDays: 12,
    departureCity: 'Mumbai (BOM)',
    departureDate: '2026-03-20',
    returnDate: '2026-04-01',
    totalSeats: 35,
    availableSeats: 3,
    pricing: {
      quadSharingInr: 295000,
      tripleSharingInr: 345000,
      doubleSharingInr: 410000,
      singleSharingInr: 580000,
    },
    costBreakdown: {
      flightFareInr: 58000,
      makkahHotelSarPerNight: 3500,
      madinahHotelSarPerNight: 1800,
      makkahNights: 7,
      madinahNights: 5,
      visaInsuranceInr: 18500,
      transportSarPerPerson: 750,
      cateringSarPerDay: 150,
      ziyaratSar: 300,
      targetMarginInr: 35000,
      gstPercentage: 5,
    },
    makkahHotelName: 'Al Safwah Royale Orchid Makkah',
    makkahHotelDistance: '0m King Abdulaziz Gate',
    madinahHotelName: 'Anwar Al Madinah Mövenpick Hotel',
    madinahHotelDistance: '0m Northern Plaza',
    airlineName: 'Air India',
    flightRoute: 'BOM ➔ JED / JED ➔ BOM',
    status: 'filling_fast',
  },
  {
    id: 'pkg-fit-custom',
    code: 'FIT-LUXURY-CUSTOM',
    title: 'Custom FIT — Tailored 5-Star Private Umrah',
    titleAr: 'برنامج عمرة خاص مفصل — كبار الشخصيات مع سيارة خاصة',
    type: 'custom_fit',
    durationDays: 10,
    departureCity: 'Mumbai / Delhi / Hyderabad',
    departureDate: '2026-10-05',
    returnDate: '2026-10-15',
    totalSeats: 10,
    availableSeats: 6,
    pricing: {
      quadSharingInr: 185000,
      tripleSharingInr: 215000,
      doubleSharingInr: 265000,
      singleSharingInr: 390000,
    },
    costBreakdown: {
      flightFareInr: 46000,
      makkahHotelSarPerNight: 1400,
      madinahHotelSarPerNight: 1100,
      makkahNights: 5,
      madinahNights: 5,
      visaInsuranceInr: 16000,
      transportSarPerPerson: 1200,
      cateringSarPerDay: 120,
      ziyaratSar: 450,
      targetMarginInr: 30000,
      gstPercentage: 5,
    },
    makkahHotelName: 'Fairmont Clock Royal Tower Makkah',
    makkahHotelDistance: '0m Clock Tower',
    madinahHotelName: 'Dar Al Taqwa Hotel Madinah',
    madinahHotelDistance: '10m Haram',
    airlineName: 'Emirates / Saudia',
    flightRoute: 'BOM ➔ DXB ➔ JED / MED ➔ BOM',
    status: 'open',
  },
];

export const INITIAL_ROOM_ALLOCATIONS: RoomAllocation[] = [
  // Makkah Swissotel Rooms
  {
    id: 'room-mk-101',
    packageBatchId: 'pkg-umrah-sep-2026',
    hotelId: 'htl-makkah-02',
    hotelCity: 'Makkah',
    roomNumber: '1402',
    floor: 14,
    roomType: 'quad',
    capacity: 4,
    genderType: 'male',
    pilgrimIds: ['plg-01', 'plg-03'],
    isFullyOccupied: false,
    notes: 'Near elevator, Kaaba side view',
  },
  {
    id: 'room-mk-102',
    packageBatchId: 'pkg-umrah-sep-2026',
    hotelId: 'htl-makkah-02',
    hotelCity: 'Makkah',
    roomNumber: '1404',
    floor: 14,
    roomType: 'quad',
    capacity: 4,
    genderType: 'female',
    pilgrimIds: ['plg-02', 'plg-04'],
    isFullyOccupied: false,
    notes: 'Connected to 1402 via corridor',
  },
  {
    id: 'room-mk-103',
    packageBatchId: 'pkg-umrah-sep-2026',
    hotelId: 'htl-makkah-02',
    hotelCity: 'Makkah',
    roomNumber: '1510',
    floor: 15,
    roomType: 'double',
    capacity: 2,
    genderType: 'family',
    pilgrimIds: ['plg-05', 'plg-06'],
    isFullyOccupied: true,
    notes: 'Elderly couple, wheelchair assistance required',
  },
  {
    id: 'room-mk-104',
    packageBatchId: 'pkg-umrah-sep-2026',
    hotelId: 'htl-makkah-02',
    hotelCity: 'Makkah',
    roomNumber: '1512',
    floor: 15,
    roomType: 'triple',
    capacity: 3,
    genderType: 'male',
    pilgrimIds: ['plg-07', 'plg-08'],
    isFullyOccupied: false,
    notes: '1 bed vacant for late assignment',
  },

  // Madinah Dar Al Taqwa Rooms
  {
    id: 'room-md-201',
    packageBatchId: 'pkg-umrah-sep-2026',
    hotelId: 'htl-madinah-02',
    hotelCity: 'Madinah',
    roomNumber: '608',
    floor: 6,
    roomType: 'quad',
    capacity: 4,
    genderType: 'male',
    pilgrimIds: ['plg-01', 'plg-03', 'plg-07'],
    isFullyOccupied: false,
    notes: 'Facing Green Dome plaza',
  },
  {
    id: 'room-md-202',
    packageBatchId: 'pkg-umrah-sep-2026',
    hotelId: 'htl-madinah-02',
    hotelCity: 'Madinah',
    roomNumber: '610',
    floor: 6,
    roomType: 'quad',
    capacity: 4,
    genderType: 'female',
    pilgrimIds: ['plg-02', 'plg-04'],
    isFullyOccupied: false,
    notes: 'Ladies courtyard view',
  },
  {
    id: 'room-md-203',
    packageBatchId: 'pkg-umrah-sep-2026',
    hotelId: 'htl-madinah-02',
    hotelCity: 'Madinah',
    roomNumber: '702',
    floor: 7,
    roomType: 'double',
    capacity: 2,
    genderType: 'family',
    pilgrimIds: ['plg-05', 'plg-06'],
    isFullyOccupied: true,
    notes: 'Quiet room near prayer room',
  },

  // Hajj 2026 Fairmont Makkah Rooms
  {
    id: 'room-hajj-mk-01',
    packageBatchId: 'pkg-hajj-jun-2026',
    hotelId: 'htl-makkah-01',
    hotelCity: 'Makkah',
    roomNumber: '2804',
    floor: 28,
    roomType: 'double',
    capacity: 2,
    genderType: 'family',
    pilgrimIds: ['plg-hajj-01', 'plg-hajj-02'],
    isFullyOccupied: true,
    notes: 'Haram facing Royal Suite for Dr. Warsi',
  },
  {
    id: 'room-hajj-mk-02',
    packageBatchId: 'pkg-hajj-jun-2026',
    hotelId: 'htl-makkah-01',
    hotelCity: 'Makkah',
    roomNumber: '2806',
    floor: 28,
    roomType: 'quad',
    capacity: 4,
    genderType: 'male',
    pilgrimIds: ['plg-hajj-03', 'plg-hajj-04'],
    isFullyOccupied: false,
    notes: 'Near elevator, Maktab #01 Shifting voucher',
  },
  {
    id: 'room-hajj-mk-03',
    packageBatchId: 'pkg-hajj-jun-2026',
    hotelId: 'htl-makkah-01',
    hotelCity: 'Makkah',
    roomNumber: '2808',
    floor: 28,
    roomType: 'quad',
    capacity: 4,
    genderType: 'female',
    pilgrimIds: ['plg-hajj-05'],
    isFullyOccupied: false,
    notes: 'Ladies section',
  },

  // Hajj 2026 Mövenpick Madinah Rooms
  {
    id: 'room-hajj-md-01',
    packageBatchId: 'pkg-hajj-jun-2026',
    hotelId: 'htl-madinah-01',
    hotelCity: 'Madinah',
    roomNumber: '1102',
    floor: 11,
    roomType: 'double',
    capacity: 2,
    genderType: 'family',
    pilgrimIds: ['plg-hajj-01', 'plg-hajj-02'],
    isFullyOccupied: true,
    notes: 'Direct Haram view',
  },
  {
    id: 'room-hajj-md-02',
    packageBatchId: 'pkg-hajj-jun-2026',
    hotelId: 'htl-madinah-01',
    hotelCity: 'Madinah',
    roomNumber: '1104',
    floor: 11,
    roomType: 'quad',
    capacity: 4,
    genderType: 'male',
    pilgrimIds: ['plg-hajj-03', 'plg-hajj-04'],
    isFullyOccupied: false,
    notes: 'Northern gate facing',
  },
];

export const INITIAL_PILGRIMS: Pilgrim[] = [
  {
    id: 'plg-01',
    bookingId: 'bk-2026-001',
    packageBatchId: 'pkg-umrah-sep-2026',
    firstName: 'Mohammed Farooq',
    lastName: 'Khan',
    passportNumber: 'Z8942109',
    passportExpiry: '2032-08-15',
    nationality: 'Indian',
    gender: 'male',
    dob: '1970-05-12',
    age: 56,
    contactNumber: '+91 98201 54321',
    email: 'farooq.khan@gmail.com',
    bloodGroup: 'B+',
    isMahramHead: true,
    relationship: 'self',
    passportFrontUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=400&q=80',
    visaStatus: 'visa_issued',
    visaNumber: '6029184710',
    mofaNumber: 'MOFA-984120',
    nusukRawdahSlot: '2026-09-18 02:30 AM',
    makkahRoomId: 'room-mk-101',
    madinahRoomId: 'room-md-201',
    busAllocationId: 'bus-01',
    flightSeatNumber: '18A',
    emergencyBadgeGenerated: true,
    subAgentId: 'agent-01',
    specialNeeds: 'Diabetic diet preference',
    notes: 'Group Leader for Khan Family (4 Pax)',
    createdAt: '2026-08-01',
  },
  {
    id: 'plg-02',
    bookingId: 'bk-2026-001',
    packageBatchId: 'pkg-umrah-sep-2026',
    firstName: 'Amina Farooq',
    lastName: 'Khan',
    passportNumber: 'Z8942110',
    passportExpiry: '2032-08-15',
    nationality: 'Indian',
    gender: 'female',
    dob: '1975-03-20',
    age: 51,
    contactNumber: '+91 98201 54322',
    bloodGroup: 'O+',
    isMahramHead: false,
    mahramId: 'plg-01',
    relationship: 'spouse',
    visaStatus: 'visa_issued',
    visaNumber: '6029184711',
    mofaNumber: 'MOFA-984121',
    nusukRawdahSlot: '2026-09-19 09:00 PM',
    makkahRoomId: 'room-mk-102',
    madinahRoomId: 'room-md-202',
    busAllocationId: 'bus-01',
    flightSeatNumber: '18B',
    emergencyBadgeGenerated: true,
    subAgentId: 'agent-01',
    createdAt: '2026-08-01',
  },
  {
    id: 'plg-03',
    bookingId: 'bk-2026-001',
    packageBatchId: 'pkg-umrah-sep-2026',
    firstName: 'Zaid Mohammed',
    lastName: 'Khan',
    passportNumber: 'Z8942111',
    passportExpiry: '2034-05-10',
    nationality: 'Indian',
    gender: 'male',
    dob: '2004-09-15',
    age: 22,
    contactNumber: '+91 98201 54323',
    bloodGroup: 'B+',
    isMahramHead: false,
    mahramId: 'plg-01',
    relationship: 'son',
    visaStatus: 'visa_issued',
    visaNumber: '6029184712',
    mofaNumber: 'MOFA-984122',
    nusukRawdahSlot: '2026-09-18 02:30 AM',
    makkahRoomId: 'room-mk-101',
    madinahRoomId: 'room-md-201',
    busAllocationId: 'bus-01',
    flightSeatNumber: '18C',
    emergencyBadgeGenerated: true,
    subAgentId: 'agent-01',
    createdAt: '2026-08-01',
  },
  {
    id: 'plg-04',
    bookingId: 'bk-2026-001',
    packageBatchId: 'pkg-umrah-sep-2026',
    firstName: 'Sara Mohammed',
    lastName: 'Khan',
    passportNumber: 'Z8942112',
    passportExpiry: '2034-05-10',
    nationality: 'Indian',
    gender: 'female',
    dob: '2007-11-28',
    age: 19,
    contactNumber: '+91 98201 54324',
    bloodGroup: 'A+',
    isMahramHead: false,
    mahramId: 'plg-01',
    relationship: 'daughter',
    visaStatus: 'visa_issued',
    visaNumber: '6029184713',
    mofaNumber: 'MOFA-984123',
    nusukRawdahSlot: '2026-09-19 09:00 PM',
    makkahRoomId: 'room-mk-102',
    madinahRoomId: 'room-md-202',
    busAllocationId: 'bus-01',
    flightSeatNumber: '18D',
    emergencyBadgeGenerated: true,
    subAgentId: 'agent-01',
    createdAt: '2026-08-01',
  },
  {
    id: 'plg-05',
    bookingId: 'bk-2026-002',
    packageBatchId: 'pkg-umrah-sep-2026',
    firstName: 'Abdul Qadir',
    lastName: 'Shaikh',
    passportNumber: 'V6391047',
    passportExpiry: '2029-11-28',
    nationality: 'Indian',
    gender: 'male',
    dob: '1952-08-10',
    age: 74,
    contactNumber: '+91 98922 77889',
    email: 'abdul.qadir@yahoo.com',
    bloodGroup: 'O+',
    isMahramHead: true,
    relationship: 'self',
    visaStatus: 'insurance_attached',
    mofaNumber: 'MOFA-984201',
    makkahRoomId: 'room-mk-103',
    madinahRoomId: 'room-md-203',
    busAllocationId: 'bus-01',
    flightSeatNumber: '12A',
    emergencyBadgeGenerated: true,
    specialNeeds: 'Wheelchair assistance required at BOM, JED, and Haramain Station',
    notes: 'Elderly couple booking with wife Fatima',
    createdAt: '2026-08-05',
  },
  {
    id: 'plg-06',
    bookingId: 'bk-2026-002',
    packageBatchId: 'pkg-umrah-sep-2026',
    firstName: 'Fatima Abdul',
    lastName: 'Shaikh',
    passportNumber: 'V6391048',
    passportExpiry: '2029-11-28',
    nationality: 'Indian',
    gender: 'female',
    dob: '1955-01-01',
    age: 71,
    contactNumber: '+91 98922 77889',
    bloodGroup: 'AB+',
    isMahramHead: false,
    mahramId: 'plg-05',
    relationship: 'spouse',
    visaStatus: 'insurance_attached',
    mofaNumber: 'MOFA-984202',
    makkahRoomId: 'room-mk-103',
    madinahRoomId: 'room-md-203',
    busAllocationId: 'bus-01',
    flightSeatNumber: '12B',
    emergencyBadgeGenerated: true,
    specialNeeds: 'Wheelchair assistance required',
    createdAt: '2026-08-05',
  },
  {
    id: 'plg-07',
    bookingId: 'bk-2026-003',
    packageBatchId: 'pkg-umrah-sep-2026',
    firstName: 'Irfan',
    lastName: 'Patel',
    passportNumber: 'W4109823',
    passportExpiry: '2031-02-14',
    nationality: 'Indian',
    gender: 'male',
    dob: '1988-06-25',
    age: 38,
    contactNumber: '+91 97654 32100',
    email: 'irfan.patel@outlook.com',
    bloodGroup: 'A+',
    isMahramHead: true,
    relationship: 'self',
    visaStatus: 'passport_submitted',
    makkahRoomId: 'room-mk-104',
    madinahRoomId: 'room-md-201',
    busAllocationId: 'bus-01',
    flightSeatNumber: '22F',
    emergencyBadgeGenerated: false,
    subAgentId: 'agent-02',
    notes: 'Traveling with colleague Zubair',
    createdAt: '2026-08-10',
  },
  {
    id: 'plg-08',
    bookingId: 'bk-2026-003',
    packageBatchId: 'pkg-umrah-sep-2026',
    firstName: 'Zubair',
    lastName: 'Siddiqui',
    passportNumber: 'T8765431',
    passportExpiry: '2030-10-09',
    nationality: 'Indian',
    gender: 'male',
    dob: '1990-12-04',
    age: 35,
    contactNumber: '+91 97654 32101',
    bloodGroup: 'B+',
    isMahramHead: false,
    mahramId: 'plg-07',
    relationship: 'group_member',
    visaStatus: 'passport_submitted',
    makkahRoomId: 'room-mk-104',
    busAllocationId: 'bus-01',
    flightSeatNumber: '22E',
    emergencyBadgeGenerated: false,
    subAgentId: 'agent-02',
    createdAt: '2026-08-10',
  },

  // Hajj 2026 VIP Pilgrims
  {
    id: 'plg-hajj-01',
    bookingId: 'bk-2026-004',
    packageBatchId: 'pkg-hajj-jun-2026',
    firstName: 'Dr. Arshad',
    lastName: 'Warsi',
    passportNumber: 'K7829104',
    passportExpiry: '2033-04-12',
    nationality: 'Indian',
    gender: 'male',
    dob: '1968-07-14',
    age: 58,
    contactNumber: '+91 98200 44556',
    email: 'arshad.warsi@fortis.com',
    bloodGroup: 'B+',
    isMahramHead: true,
    relationship: 'self',
    visaStatus: 'visa_issued',
    visaNumber: '6038194012',
    mofaNumber: 'MOFA-HAJJ-88120',
    nusukRawdahSlot: '2026-05-24 03:00 AM',
    makkahRoomId: 'room-hajj-mk-01',
    madinahRoomId: 'room-hajj-md-01',
    busAllocationId: 'bus-01',
    flightSeatNumber: '04A',
    emergencyBadgeGenerated: true,
    specialNeeds: 'Executive VIP Transfer required',
    notes: 'Senior Neurologist traveling with wife Parveen',
    createdAt: '2026-08-12',
  },
  {
    id: 'plg-hajj-02',
    bookingId: 'bk-2026-004',
    packageBatchId: 'pkg-hajj-jun-2026',
    firstName: 'Parveen Arshad',
    lastName: 'Warsi',
    passportNumber: 'K7829105',
    passportExpiry: '2033-04-12',
    nationality: 'Indian',
    gender: 'female',
    dob: '1972-11-05',
    age: 54,
    contactNumber: '+91 98200 44556',
    bloodGroup: 'O+',
    isMahramHead: false,
    mahramId: 'plg-hajj-01',
    relationship: 'spouse',
    visaStatus: 'visa_issued',
    visaNumber: '6038194013',
    mofaNumber: 'MOFA-HAJJ-88121',
    nusukRawdahSlot: '2026-05-25 09:30 PM',
    makkahRoomId: 'room-hajj-mk-01',
    madinahRoomId: 'room-hajj-md-01',
    busAllocationId: 'bus-01',
    flightSeatNumber: '04B',
    emergencyBadgeGenerated: true,
    createdAt: '2026-08-12',
  },
  {
    id: 'plg-hajj-03',
    bookingId: 'bk-2026-005',
    packageBatchId: 'pkg-hajj-jun-2026',
    firstName: 'Haji Bashir',
    lastName: 'Patel',
    passportNumber: 'P9012488',
    passportExpiry: '2031-09-20',
    nationality: 'Indian',
    gender: 'male',
    dob: '1962-02-18',
    age: 64,
    contactNumber: '+91 98210 99881',
    bloodGroup: 'A+',
    isMahramHead: true,
    relationship: 'self',
    visaStatus: 'mofa_generated',
    mofaNumber: 'MOFA-HAJJ-88135',
    makkahRoomId: 'room-hajj-mk-02',
    madinahRoomId: 'room-hajj-md-02',
    busAllocationId: 'bus-01',
    flightSeatNumber: '08C',
    emergencyBadgeGenerated: true,
    createdAt: '2026-08-15',
  },
  {
    id: 'plg-hajj-04',
    bookingId: 'bk-2026-005',
    packageBatchId: 'pkg-hajj-jun-2026',
    firstName: 'Tariq Bashir',
    lastName: 'Patel',
    passportNumber: 'P9012489',
    passportExpiry: '2035-01-10',
    nationality: 'Indian',
    gender: 'male',
    dob: '1995-06-12',
    age: 31,
    contactNumber: '+91 98210 99882',
    bloodGroup: 'A+',
    isMahramHead: false,
    mahramId: 'plg-hajj-03',
    relationship: 'son',
    visaStatus: 'mofa_generated',
    mofaNumber: 'MOFA-HAJJ-88136',
    makkahRoomId: 'room-hajj-mk-02',
    madinahRoomId: 'room-hajj-md-02',
    busAllocationId: 'bus-01',
    flightSeatNumber: '08D',
    emergencyBadgeGenerated: true,
    createdAt: '2026-08-15',
  },
  {
    id: 'plg-hajj-05',
    bookingId: 'bk-2026-005',
    packageBatchId: 'pkg-hajj-jun-2026',
    firstName: 'Rashida Bashir',
    lastName: 'Patel',
    passportNumber: 'P9012490',
    passportExpiry: '2031-09-20',
    nationality: 'Indian',
    gender: 'female',
    dob: '1966-08-22',
    age: 60,
    contactNumber: '+91 98210 99881',
    bloodGroup: 'B+',
    isMahramHead: false,
    mahramId: 'plg-hajj-03',
    relationship: 'spouse',
    visaStatus: 'passport_submitted',
    makkahRoomId: 'room-hajj-mk-03',
    busAllocationId: 'bus-01',
    flightSeatNumber: '09A',
    emergencyBadgeGenerated: false,
    createdAt: '2026-08-15',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-2026-001',
    bookingNumber: 'CTT-2026-089',
    leadId: 'lead-01',
    primaryContactName: 'Mohammed Farooq Khan',
    primaryContactPhone: '+91 98201 54321',
    primaryContactEmail: 'farooq.khan@gmail.com',
    city: 'Mumbai',
    packageBatchId: 'pkg-umrah-sep-2026',
    pilgrimCount: 4,
    pilgrimIds: ['plg-01', 'plg-02', 'plg-03', 'plg-04'],
    totalAmountInr: 552000,
    paidAmountInr: 400000,
    balanceAmountInr: 152000,
    status: 'confirmed',
    subAgentId: 'agent-01',
    agentCommissionInr: 22080,
    bookedAt: '2026-08-01',
    departureDate: '2026-09-15',
    returnDate: '2026-09-30',
    gstNumber: '27AABCU9603R1ZM',
    specialRequests: 'Adjoining rooms for family in Makkah & Madinah',
  },
  {
    id: 'bk-2026-002',
    bookingNumber: 'CTT-2026-094',
    primaryContactName: 'Abdul Qadir Shaikh',
    primaryContactPhone: '+91 98922 77889',
    primaryContactEmail: 'abdul.qadir@yahoo.com',
    city: 'Mumbai',
    packageBatchId: 'pkg-umrah-sep-2026',
    pilgrimCount: 2,
    pilgrimIds: ['plg-05', 'plg-06'],
    totalAmountInr: 350000,
    paidAmountInr: 350000,
    balanceAmountInr: 0,
    status: 'confirmed',
    bookedAt: '2026-08-05',
    departureDate: '2026-09-15',
    returnDate: '2026-09-30',
    specialRequests: '2 Wheelchairs & porter assistance on all legs',
  },
  {
    id: 'bk-2026-003',
    bookingNumber: 'CTT-2026-102',
    primaryContactName: 'Irfan Patel',
    primaryContactPhone: '+91 97654 32100',
    primaryContactEmail: 'irfan.patel@outlook.com',
    city: 'Pune',
    packageBatchId: 'pkg-umrah-sep-2026',
    pilgrimCount: 2,
    pilgrimIds: ['plg-07', 'plg-08'],
    totalAmountInr: 304000,
    paidAmountInr: 100000,
    balanceAmountInr: 204000,
    status: 'deposit_paid',
    subAgentId: 'agent-02',
    agentCommissionInr: 12160,
    bookedAt: '2026-08-10',
    departureDate: '2026-09-15',
    returnDate: '2026-09-30',
  },
];

export const INITIAL_TRANSPORTS: TransportAllocation[] = [
  {
    id: 'bus-01',
    packageBatchId: 'pkg-umrah-sep-2026',
    vehicleType: 'bus_45',
    vehicleNumber: 'KSA-7821-B (SAPTCCO Luxury)',
    capacity: 45,
    driverName: 'Tariq Al-Masri',
    driverPhone: '+966 55 491 8820',
    ameerLeaderName: 'Maulana Imran Shaikh',
    ameerLeaderPhone: '+966 50 123 4567',
    routeName: 'JED Airport (T1) ➔ Makkah Swissôtel Hotel',
    routeDate: '2026-09-15 16:30',
    pilgrimIds: ['plg-01', 'plg-02', 'plg-03', 'plg-04', 'plg-05', 'plg-06', 'plg-07', 'plg-08'],
    luggageCount: 18,
    status: 'scheduled',
  },
  {
    id: 'bus-02',
    packageBatchId: 'pkg-umrah-sep-2026',
    vehicleType: 'bus_45',
    vehicleNumber: 'KSA-9144-A (Mercedes Travego)',
    capacity: 45,
    driverName: 'Mustafa Al-Ghamdi',
    driverPhone: '+966 53 881 2290',
    ameerLeaderName: 'Maulana Imran Shaikh',
    ameerLeaderPhone: '+966 50 123 4567',
    routeName: 'Makkah Hotel ➔ Madinah Dar Al Taqwa (Haramain Ziyarat Route)',
    routeDate: '2026-09-23 09:00',
    pilgrimIds: ['plg-01', 'plg-02', 'plg-03', 'plg-04', 'plg-05', 'plg-06', 'plg-07', 'plg-08'],
    luggageCount: 18,
    status: 'scheduled',
  },
  {
    id: 'gmc-01',
    packageBatchId: 'pkg-fit-custom',
    vehicleType: 'gmc_yukon',
    vehicleNumber: 'KSA-3301-VIP (GMC Yukon XL 2025)',
    capacity: 7,
    driverName: 'Abu Bakr Al-Sudani',
    driverPhone: '+966 54 332 9901',
    ameerLeaderName: 'Hafiz Bilal Ahmed',
    ameerLeaderPhone: '+966 59 888 1234',
    routeName: 'Private VIP Ziyarat: Jabal Al-Noor, Jabal Thawr, Mina & Arafat',
    routeDate: '2026-09-18 07:00',
    pilgrimIds: ['plg-01', 'plg-02', 'plg-03', 'plg-04'],
    luggageCount: 4,
    status: 'scheduled',
  },
];

export const INITIAL_FLIGHTS: FlightManifest[] = [
  {
    id: 'flt-01',
    packageBatchId: 'pkg-umrah-sep-2026',
    airline: 'Saudia (Saudi Arabian Airlines)',
    flightNumber: 'SV 741',
    pnr: 'W9X7KP',
    departureAirport: 'BOM - Mumbai Chhatrapati Shivaji Maharaj T2',
    arrivalAirport: 'JED - King Abdulaziz Intl Airport Jeddah T1',
    departureTime: '2026-09-15 11:45',
    arrivalTime: '2026-09-15 14:15',
    totalSeatsBlocked: 45,
    seatsAllocated: 33,
    pilgrimSeatMap: [
      { pilgrimId: 'plg-01', seatNumber: '18A', bagTagNumber: 'SV-BOM-89210', checkedIn: true },
      { pilgrimId: 'plg-02', seatNumber: '18B', bagTagNumber: 'SV-BOM-89211', checkedIn: true },
      { pilgrimId: 'plg-03', seatNumber: '18C', bagTagNumber: 'SV-BOM-89212', checkedIn: false },
      { pilgrimId: 'plg-04', seatNumber: '18D', bagTagNumber: 'SV-BOM-89213', checkedIn: false },
      { pilgrimId: 'plg-05', seatNumber: '12A', bagTagNumber: 'SV-BOM-89214', checkedIn: true },
      { pilgrimId: 'plg-06', seatNumber: '12B', bagTagNumber: 'SV-BOM-89215', checkedIn: true },
      { pilgrimId: 'plg-07', seatNumber: '22F', bagTagNumber: 'SV-BOM-89216', checkedIn: false },
      { pilgrimId: 'plg-08', seatNumber: '22E', bagTagNumber: 'SV-BOM-89217', checkedIn: false },
    ],
  },
  {
    id: 'flt-02',
    packageBatchId: 'pkg-umrah-sep-2026',
    airline: 'Saudia (Saudi Arabian Airlines)',
    flightNumber: 'SV 742',
    pnr: 'W9X7KP',
    departureAirport: 'MED - Prince Mohammad Bin Abdulaziz Airport Madinah',
    arrivalAirport: 'BOM - Mumbai Chhatrapati Shivaji Maharaj T2',
    departureTime: '2026-09-30 18:30',
    arrivalTime: '2026-10-01 02:15',
    totalSeatsBlocked: 45,
    seatsAllocated: 33,
    pilgrimSeatMap: [],
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-01',
    name: 'Dr. Arshad Warsi',
    phone: '+91 98334 11223',
    email: 'arshad.warsi@fortis.com',
    city: 'Mumbai',
    source: 'website_form',
    interestType: 'Hajj 2026',
    paxCount: 3,
    budgetInr: 2500000,
    assignedTo: 'Salim Merchant (Senior Sales)',
    status: 'quotation_sent',
    leadScore: 92,
    lastContactedAt: '2026-08-20',
    followUpDate: '2026-08-22',
    notes: 'Interested in VIP Executive Shifting package with Double sharing room.',
    createdAt: '2026-08-15',
  },
  {
    id: 'lead-02',
    name: 'Zameer Qureshi',
    phone: '+91 99200 44556',
    email: 'zameer@qureshigroup.in',
    city: 'Navi Mumbai',
    source: 'whatsapp',
    interestType: 'Ramadan Special',
    paxCount: 6,
    budgetInr: 1800000,
    assignedTo: 'Faizan Ansari',
    status: 'doc_followup',
    leadScore: 85,
    lastContactedAt: '2026-08-19',
    followUpDate: '2026-08-21',
    notes: 'Passports received for 4 pax, awaiting 2 renewal copies.',
    createdAt: '2026-08-12',
  },
  {
    id: 'lead-03',
    name: 'Sayed Nadeem Akhtar',
    phone: '+91 97022 99881',
    city: 'Thane',
    source: 'facebook_ad',
    interestType: 'Umrah Group',
    paxCount: 2,
    budgetInr: 300000,
    assignedTo: 'Salim Merchant (Senior Sales)',
    status: 'new_inquiry',
    leadScore: 70,
    lastContactedAt: '2026-08-21',
    followUpDate: '2026-08-21',
    notes: 'Inquired from Facebook Ad campaign for October Umrah.',
    createdAt: '2026-08-21',
  },
  {
    id: 'lead-04',
    name: 'Iqbal Kazi',
    phone: '+91 98210 66778',
    city: 'Ratnagiri',
    source: 'walk_in',
    interestType: 'VIP Custom FIT',
    paxCount: 4,
    budgetInr: 1200000,
    assignedTo: 'Aamir Khan (Branch Head)',
    status: 'deposit_paid',
    leadScore: 98,
    lastContactedAt: '2026-08-18',
    followUpDate: '2026-08-25',
    notes: 'Paid ₹1,00,000 token advance in cash at Crawford Market office.',
    createdAt: '2026-08-10',
  },
  {
    id: 'lead-05',
    name: 'Advocate Shahnawaz Shaikh',
    phone: '+91 98199 33221',
    city: 'Mumbai',
    source: 'b2b_referral',
    interestType: 'Umrah Group',
    paxCount: 5,
    budgetInr: 750000,
    assignedTo: 'Faizan Ansari',
    status: 'confirmed',
    leadScore: 95,
    lastContactedAt: '2026-08-16',
    followUpDate: '2026-09-01',
    notes: 'Converted to Booking CTT-2026-089.',
    createdAt: '2026-08-01',
  },
];

export const INITIAL_SUB_AGENTS: SubAgent[] = [
  {
    id: 'agent-01',
    agencyName: 'Al-Barkat Tours & Travels',
    contactPerson: 'Haji Rizwan Memon',
    city: 'Mumbai (Kurla West)',
    phone: '+91 98205 99887',
    email: 'albarkat.tours@gmail.com',
    walletBalanceInr: 450000,
    creditLimitInr: 1000000,
    commissionPercentage: 4.0,
    totalBookings: 18,
    totalPilgrims: 76,
    status: 'active',
    whiteLabelSettings: {
      brandName: 'Al-Barkat Tours Mumbai',
      contactPhone: '+91 98205 99887',
      supportEmail: 'support@albarkattours.com',
    },
  },
  {
    id: 'agent-02',
    agencyName: 'Deen Travel Services',
    contactPerson: 'Maulana Asif Patel',
    city: 'Pune (Camp)',
    phone: '+91 98601 22334',
    email: 'deentravelspune@yahoo.com',
    walletBalanceInr: 185000,
    creditLimitInr: 500000,
    commissionPercentage: 4.0,
    totalBookings: 11,
    totalPilgrims: 42,
    status: 'active',
    whiteLabelSettings: {
      brandName: 'Deen Travels Pune',
      contactPhone: '+91 98601 22334',
      supportEmail: 'info@deentravels.in',
    },
  },
  {
    id: 'agent-03',
    agencyName: 'Al-Hidayah Hajj & Umrah Services',
    contactPerson: 'Sohail Baig',
    city: 'Hyderabad (Charminar)',
    phone: '+91 98490 88776',
    email: 'alhidayah.hyd@gmail.com',
    walletBalanceInr: 820000,
    creditLimitInr: 1500000,
    commissionPercentage: 4.5,
    totalBookings: 26,
    totalPilgrims: 114,
    status: 'active',
    whiteLabelSettings: {
      brandName: 'Al-Hidayah Hyderabad',
      contactPhone: '+91 98490 88776',
      supportEmail: 'contact@alhidayahhyd.com',
    },
  },
  {
    id: 'agent-04',
    agencyName: 'Noor International Travels',
    contactPerson: 'Tanveer Ahmed',
    city: 'Bangalore (Shivajinagar)',
    phone: '+91 98800 11992',
    email: 'noortravels.blr@gmail.com',
    walletBalanceInr: 95000,
    creditLimitInr: 400000,
    commissionPercentage: 3.5,
    totalBookings: 6,
    totalPilgrims: 24,
    status: 'active',
    whiteLabelSettings: {
      brandName: 'Noor International Bangalore',
      contactPhone: '+91 98800 11992',
      supportEmail: 'help@noortravels.com',
    },
  },
];

export const INITIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 'txn-01',
    bookingId: 'bk-2026-001',
    packageBatchId: 'pkg-umrah-sep-2026',
    subAgentId: 'agent-01',
    transactionType: 'customer_receipt',
    description: 'Booking Advance Payment received for Khan Family (4 Pax)',
    descriptionAr: 'استلام دفعة مقدمة لحجز عائلة خان (4 معتمرين)',
    currency: 'INR',
    amount: 400000,
    exchangeRate: 1.0,
    amountInr: 400000,
    paymentMode: 'Bank Transfer',
    referenceNumber: 'NEFT-HDFC-9842104921',
    receiptNumber: 'REC-2026-041',
    createdAt: '2026-08-01 14:30',
    status: 'verified',
  },
  {
    id: 'txn-02',
    bookingId: 'bk-2026-002',
    packageBatchId: 'pkg-umrah-sep-2026',
    transactionType: 'customer_receipt',
    description: 'Full Payment received for Shaikh Couple (2 Pax)',
    descriptionAr: 'استلام السداد الكامل لحجز عائلة الشيخ (2 معتمرين)',
    currency: 'INR',
    amount: 350000,
    exchangeRate: 1.0,
    amountInr: 350000,
    paymentMode: 'UPI',
    referenceNumber: 'UPI-ICICI-20260805114890',
    receiptNumber: 'REC-2026-042',
    createdAt: '2026-08-05 11:15',
    status: 'verified',
  },
  {
    id: 'txn-03',
    packageBatchId: 'pkg-umrah-sep-2026',
    supplierId: 'htl-makkah-02',
    transactionType: 'supplier_payment',
    description: 'Advance Deposit for 15 Rooms at Swissôtel Al Maqam Makkah',
    descriptionAr: 'دفعة مقدمة لحجز 15 غرفة في فندق سويس أوتيل المقام مكة',
    currency: 'SAR',
    amount: 42750, // 42,750 SAR
    exchangeRate: 22.35,
    amountInr: 955462.5,
    paymentMode: 'Saudi Bank SNB',
    referenceNumber: 'SNB-TT-KSA-9014285',
    receiptNumber: 'VOUCH-MK-8821',
    createdAt: '2026-08-08 16:00',
    status: 'verified',
  },
  {
    id: 'txn-04',
    packageBatchId: 'pkg-umrah-sep-2026',
    supplierId: 'htl-madinah-02',
    transactionType: 'supplier_payment',
    description: 'Advance Deposit for 15 Rooms at Dar Al Taqwa Madinah',
    descriptionAr: 'دفعة مقدمة لحجز 15 غرفة في فندق دار التقوى بالمدينة المنورة',
    currency: 'SAR',
    amount: 33750, // 33,750 SAR
    exchangeRate: 22.35,
    amountInr: 754312.5,
    paymentMode: 'Saudi Bank SNB',
    referenceNumber: 'SNB-TT-KSA-9014299',
    receiptNumber: 'VOUCH-MD-4412',
    createdAt: '2026-08-09 12:45',
    status: 'verified',
  },
  {
    id: 'txn-05',
    bookingId: 'bk-2026-001',
    subAgentId: 'agent-01',
    transactionType: 'agent_commission',
    description: '4% Sub-Agent Commission credited to Al-Barkat Tours Wallet',
    descriptionAr: 'إيداع عمولة الوكيل 4% في محفظة وكالة البركات',
    currency: 'INR',
    amount: 22080,
    exchangeRate: 1.0,
    amountInr: 22080,
    paymentMode: 'Wallet',
    referenceNumber: 'COMM-ALBARKAT-20260801',
    receiptNumber: 'COMM-VCH-102',
    createdAt: '2026-08-01 15:00',
    status: 'verified',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-01',
    timestamp: '2026-08-21 10:45:12',
    userRole: 'ops_manager',
    userName: 'Tariq Siddiqui (Ops Head)',
    action: 'ROOM_ALLOCATION_UPDATED',
    module: 'GroundOps',
    details: 'Assigned Mohammed Farooq Khan (plg-01) and Zaid Khan (plg-03) to Swissotel Makkah Room #1402',
    ipAddress: '103.21.144.62 (Mumbai HQ)',
  },
  {
    id: 'log-02',
    timestamp: '2026-08-21 09:30:45',
    userRole: 'visa_officer',
    userName: 'Rashid Khan (Visa Desk)',
    action: 'VISA_ISSUED_STATUS_CHANGED',
    module: 'VisaNusuk',
    details: 'Updated Visa Milestone for Khan Family (4 Pilgrims) to VISA_ISSUED with MoFA reference MOFA-984120',
    ipAddress: '103.21.144.62 (Mumbai HQ)',
  },
  {
    id: 'log-03',
    timestamp: '2026-08-20 17:15:00',
    userRole: 'accountant',
    userName: 'Farhan Sayed (Finance Manager)',
    action: 'SUPPLIER_DISBURSEMENT_RECORDED',
    module: 'Finance',
    details: 'Disbursed SAR 42,750 via SNB Bank Transfer to Swissotel Makkah (VOUCH-MK-8821)',
    ipAddress: '103.21.144.65',
  },
  {
    id: 'log-04',
    timestamp: '2026-08-20 14:22:18',
    userRole: 'sales_exec',
    userName: 'Salim Merchant (Senior Sales)',
    action: 'LEAD_QUOTATION_GENERATED',
    module: 'CRM',
    details: 'Generated and dispatched WhatsApp quotation for Dr. Arshad Warsi (3 Pax Hajj VIP)',
    ipAddress: '103.21.144.70',
  },
  {
    id: 'log-05',
    timestamp: '2026-08-19 11:10:05',
    userRole: 'saudi_ameer',
    userName: 'Maulana Imran Shaikh (Ground Ameer)',
    action: 'BUS_MANIFEST_SYNCED',
    module: 'GroundOps',
    details: 'Synced Bus #01 manifest with Jeddah Airport Reception Desk for 8 arriving pilgrims',
    ipAddress: '212.119.64.12 (Jeddah, Saudi Arabia)',
  },
];

export const INITIAL_WHATSAPP_MESSAGES: any[] = [
  {
    id: 'wa-msg-01',
    recipientPhone: '+91 98201 54321',
    recipientName: 'Mohammed Farooq Khan',
    templateType: 'booking_confirmation',
    messageText: 'Assalamu Alaikum *Mohammed Farooq Khan*,\n\nYour booking with *Classic Tour & Travels* (Mumbai HQ) has been confirmed!\n\n📋 *Booking Ref:* CTT-2026-089\n🕋 *Package:* Umrah Autumn Deluxe 15 Days\n👥 *Pilgrims:* 4 Pax\n💳 *Amount Paid:* ₹4,00,000 (Balance: ₹1,52,000)\n\nJazakAllah Khair for choosing Classic Tour & Travels.',
    status: 'delivered',
    timestamp: '2026-08-20 14:30',
  },
  {
    id: 'wa-msg-02',
    recipientPhone: '+91 98200 44556',
    recipientName: 'Dr. Arshad Warsi',
    templateType: 'visa_issued',
    messageText: 'Assalamu Alaikum *Dr. Arshad Warsi*,\n\nAlhamdulillah! Your Saudi E-Visa for Hajj 2026 VIP has been approved and issued by the Saudi Ministry of Foreign Affairs (MoFA).\n\n📄 *Saudi E-Visa Number:* 6038194012\n🏛️ *MoFA Reference:* MOFA-HAJJ-88120\n\nMay Allah accept your pilgrimage.',
    status: 'read',
    timestamp: '2026-08-21 09:15',
  },
];
